### ISSUE TITLE
aws domain

### ISSUE THREAD

**Issue by talha-abdullah-990** [ScotchSource/StreamingRadioRailsIceast#1]
Hello,

my streaming is working on this ip http://18.237.207.146/ . But after configure ip over domain (https://arabic.prazor.com/) it is not working on the domain 
can you please help me which files i have to change . 
thanks

**Comment by bodrovis** [comment]
Good day! I will try to check though I haven't worked with Icecast in a while :)

**Comment by bodrovis** [comment]
This is what you're looking for, I believe https://icecast.org/docs/icecast-latest/config-file.html (check the **Misc Server Settings** section) - you can provide hostname, port, and stuff like that.
